### ISSUE TITLE
WSL running bootstrap script error & ruby installation failure

### ISSUE THREAD

**Issue by jberroa** [jldeen/dotfiles#22]
Pull Request to fix issue: https://github.com/jldeen/dotfiles/pull/24

https://github.com/jldeen/dotfiles/blob/04b67c076a586bd140adedfd563faa98754f61a8/script/bootstrap#L57
Then line above causes the following error:
 `./bootstrap: line 58: syntax error near unexpected token )' `

```
setup_ruby () {
  while true; do
    read -p "Do you want to install and configure Ruby" yn
    case $yn in
        [Yy]* ) installRuby; break;;
        [Nn]* ) echo "Not installing ruby..."
        * ) echo "Please answer yes or no.";;
    esac
done
}
```
Then line above causes the following error:
 `./bootstrap: line 58: syntax error near unexpected token )' `

The line below should fix the problem 
`[Nn]* ) echo "Not installing ruby...";break;;`

Also once the bootstrap file is fixed when it installs ruby you get the following error 
```
Running doctor script to verify installation...
Checking for `rbenv' in PATH: not found
  You seem to have rbenv installed in `/home/jorge/.rbenv/bin', but that
  directory is not present in PATH. Please add it to PATH by configuring
  your `~/.bashrc', `~/.zshrc', or `~/.config/fish/config.fish'.
```

**Comment by jldeen** [comment]
Fixed in PR #24
