### ISSUE TITLE
wls ubuntu 20.04 : setup failed and left a weird terminal

### ISSUE THREAD

**Issue by AllieUbisse** [jldeen/dotfiles#25]
## Error:
 /home/**username**/.dotfiles/script/bootstrap: line 58: syntax error near unexpected token `)'  jldeen's dotfiles were not applied successfully...

![Screenshot (16)](https://user-images.githubusercontent.com/60136259/81488512-edf99680-9269-11ea-89df-772676ea969c.png)
---
Please assist
I am a fan of the Linux custom terminal.

**Comment by JorgeBerroa** [comment]
I made a pull request that fixes that issue. You can just edit your bootstrap file locally and run it again to make it work. Also to get rid of those weird characters make sure to have the font installed on your machine.

**Comment by jldeen** [comment]
The PR #24 @JorgeBerroa mentions has been merged, you should retry the install and report back if there are still issues. Thanks!
